# Generated by the asset_copier plugin
# http://github.com/pelargir/asset_copier

require File.expand_path(File.dirname(__FILE__) + '/../lib/spread/asset_copier')

namespace :spread do
  desc "Install files required by spread"
  task :install do  
    Spread::AssetCopier.copy "spread"
  end
end